spring:
    application:
        name: cruncher
    datasource:
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/vagrant
        username: vagrant
        password: vagrant
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      show-sql: false
      hibernate.ddl-auto: create
server:
    port: 8888